#define MAX_FLUID 300
#define VERY_CLOSE_FLUID 280
#define CLOSE_FLUID 200
#define MEDIUM_FLUID 150
#define MIN_FLUID 0

#define MIN_FLUID_SPAWN 100
#define MAX_FLUID_SPAWN 200

#define HAS_NO_FLUID_COUNT 1
#define MEDIUM_FLUID_COUNT 2
#define OVERCHARGED_FLUID_COUNT 3
