/datum/asset/spritesheet/simple/paper
	name = "paper"
	assets = list(
		"stamp-clown"              = 'icons/stamp_icons/legit/large_stamp-clown.png',
		"stamp-deny"               = 'icons/stamp_icons/legit/large_stamp-deny.png',
		"stamp-ok"                 = 'icons/stamp_icons/legit/large_stamp-ok.png',
		"stamp-hop"                = 'icons/stamp_icons/legit/large_stamp-hop.png',
		"stamp-cmo"                = 'icons/stamp_icons/legit/large_stamp-cmo.png',
		"stamp-ce"                 = 'icons/stamp_icons/legit/large_stamp-ce.png',
		"stamp-hos"                = 'icons/stamp_icons/legit/large_stamp-hos.png',
		"stamp-rd"                 = 'icons/stamp_icons/legit/large_stamp-rd.png',
		"stamp-cap"                = 'icons/stamp_icons/legit/large_stamp-cap.png',
		"stamp-com"                = 'icons/stamp_icons/legit/large_stamp-com.png',
		"stamp-qm"                 = 'icons/stamp_icons/legit/large_stamp-qm.png',
		"stamp-law"                = 'icons/stamp_icons/legit/large_stamp-law.png',
		"stamp-chap"               = 'icons/stamp_icons/legit/large_stamp-chap.png',
		"stamp-mime"               = 'icons/stamp_icons/legit/large_stamp-mime.png',
		"stamp-centcom"            = 'icons/stamp_icons/legit/large_stamp-centcom.png',
		"stamp-syndicate"          = 'icons/stamp_icons/legit/large_stamp-syndicate.png',
		"stamp-ntr"                = 'icons/stamp_icons/legit/large_stamp-rep.png',
		"stamp-warden"             = 'icons/stamp_icons/legit/large_stamp-warden.png',
		"stamp-security"           = 'icons/stamp_icons/legit/large_stamp-security.png',
		"stamp-machine"            = 'icons/stamp_icons/legit/large_stamp-machine.png', // BLUEMOON ADD - новый штамп для автоматически сгененированных документов
		"stamp-solgov"             = 'icons/stamp_icons/legit/large_stamp-solgov.png', // BLUEMOON ADD - новый штамп для аванпоста
		"stamp-record"             = 'icons/stamp_icons/legit/large_stamp-record.png', // BLUEMOON ADD - новый штамп для транскрайбера текста

		// BLUEMOON ADD - поддельные штампы хорошего качества
		"fake-gud-stamp-clown"     = 'icons/stamp_icons/fake_good/good_false_large_stamp-clown.png',
		"fake-gud-stamp-hop"       = 'icons/stamp_icons/fake_good/good_false_large_stamp-hop.png',
		"fake-gud-stamp-cmo"       = 'icons/stamp_icons/fake_good/good_false_large_stamp-cmo.png',
		"fake-gud-stamp-ce"        = 'icons/stamp_icons/fake_good/good_false_large_stamp-ce.png',
		"fake-gud-stamp-hos"       = 'icons/stamp_icons/fake_good/good_false_large_stamp-hos.png',
		"fake-gud-stamp-rd"        = 'icons/stamp_icons/fake_good/good_false_large_stamp-rd.png',
		"fake-gud-stamp-cap"       = 'icons/stamp_icons/fake_good/good_false_large_stamp-cap.png',
		"fake-gud-stamp-com"       = 'icons/stamp_icons/fake_good/good_false_large_stamp-com.png',
		"fake-gud-stamp-qm"        = 'icons/stamp_icons/fake_good/good_false_large_stamp-qm.png',
		"fake-gud-stamp-law"       = 'icons/stamp_icons/fake_good/good_false_large_stamp-law.png',
		"fake-gud-stamp-syndicate" = 'icons/stamp_icons/fake_good/good_false_large_stamp-syndicate.png',
		"fake-gud-stamp-ntr"       = 'icons/stamp_icons/fake_good/good_false_large_stamp-rep.png',
		"fake-gud-stamp-warden"    = 'icons/stamp_icons/fake_good/good_false_large_stamp-warden.png',
		"fake-gud-stamp-security"  = 'icons/stamp_icons/fake_good/good_false_large_stamp-security.png',

		// BLUEMOON ADD - поддельные штампы среднего качества
		"fake-mid-stamp-clown"     = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-clown.png',
		"fake-mid-stamp-hop"       = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-hop.png',
		"fake-mid-stamp-cmo"       = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-cmo.png',
		"fake-mid-stamp-ce"	       = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-ce.png',
		"fake-mid-stamp-hos"       = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-hos.png',
		"fake-mid-stamp-rd"        = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-rd.png',
		"fake-mid-stamp-cap"       = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-cap.png',
		"fake-mid-stamp-com"       = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-com.png',
		"fake-mid-stamp-qm"	       = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-qm.png',
		"fake-mid-stamp-law"       = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-law.png',
		"fake-mid-stamp-syndicate" = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-syndicate.png',
		"fake-mid-stamp-ntr"       = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-rep.png',
		"fake-mid-stamp-warden"    = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-warden.png',
		"fake-mid-stamp-security"  = 'icons/stamp_icons/fake_mid/normal_false_large_stamp-security.png',

		// BLUEMOON ADD - поддельные штампы плохого качества
		"fake-bad-stamp-clown"     = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-clown.png',
		"fake-bad-stamp-hop"       = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-hop.png',
		"fake-bad-stamp-cmo"       = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-cmo.png',
		"fake-bad-stamp-ce"	       = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-ce.png',
		"fake-bad-stamp-hos"       = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-hos.png',
		"fake-bad-stamp-rd"        = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-rd.png',
		"fake-bad-stamp-cap"       = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-cap.png',
		"fake-bad-stamp-com"       = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-com.png',
		"fake-bad-stamp-qm"	       = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-qm.png',
		"fake-bad-stamp-law"       = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-law.png',
		"fake-bad-stamp-syndicate" = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-syndicate.png',
		"fake-bad-stamp-ntr"       = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-rep.png',
		"fake-bad-stamp-warden"    = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-warden.png',
		"fake-bad-stamp-security"  = 'icons/stamp_icons/fake_bad/worst_false_large_stamp-security.png',
	)
